import { Product } from './types'

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Kenyan Pride Bracelet',
    description: 'This stunning handcrafted bracelet embodies the spirit of Kenya through its vibrant beadwork in the colors of the national flag. Each bead is carefully selected and woven by skilled Maasai artisans using traditional techniques passed down through generations. The black beads represent the people of Kenya, red symbolizes the blood shed for independence, white stands for peace, and green represents the country\'s natural wealth.',
    handle: 'kenyan-pride-bracelet',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v1-s', title: 'Small', prices: [{ amount: 2500, currency_code: 'usd' }], inventory_quantity: 20 },
      { id: 'v1-m', title: 'Medium', prices: [{ amount: 2500, currency_code: 'usd' }], inventory_quantity: 25 },
      { id: 'v1-l', title: 'Large', prices: [{ amount: 2500, currency_code: 'usd' }], inventory_quantity: 15 },
    ],
    tags: [{ value: 'bracelets' }, { value: 'red' }, { value: 'featured' }],
  },
  {
    id: '2',
    title: 'Maasai Heritage Necklace',
    description: 'A stunning necklace featuring intricate Maasai beadwork patterns representing heritage and tradition. This statement piece combines traditional craftsmanship with contemporary style. Each necklace is handcrafted with precision and care, featuring authentic Maasai patterns that have been used for generations.',
    handle: 'maasai-heritage-necklace',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v2', title: 'Classic', prices: [{ amount: 4500, currency_code: 'usd' }], inventory_quantity: 12 },
    ],
    tags: [{ value: 'necklaces' }, { value: 'green' }, { value: 'featured' }],
  },
  {
    id: '3',
    title: 'Unity Anklet',
    description: 'Delicate anklet featuring white and green beads representing peace and prosperity. Perfect for everyday wear or special occasions. The adjustable design ensures a comfortable fit for all ankle sizes. Handcrafted by Maasai women artisans.',
    handle: 'unity-anklet',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v3', title: 'Adjustable', prices: [{ amount: 2000, currency_code: 'usd' }], inventory_quantity: 30 },
    ],
    tags: [{ value: 'anklets' }, { value: 'white' }, { value: 'featured' }],
  },
  {
    id: '4',
    title: 'Warrior Spirit Bracelet',
    description: 'A powerful bracelet featuring black and red beads, inspired by the strength and courage of Maasai warriors. This bold design makes a statement while honoring traditional Maasai culture. Each bracelet is handcrafted with durable materials for long-lasting wear.',
    handle: 'warrior-spirit-bracelet',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v4', title: 'Medium', prices: [{ amount: 3000, currency_code: 'usd' }], inventory_quantity: 18 },
    ],
    tags: [{ value: 'bracelets' }, { value: 'black' }, { value: 'featured' }],
  },
  {
    id: '5',
    title: 'Heritage Choker',
    description: 'An elegant choker featuring traditional Maasai patterns in vibrant red beads. A statement piece for any occasion. This stunning necklace sits beautifully at the collarbone and pairs perfectly with both casual and formal attire.',
    handle: 'heritage-choker',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v5', title: 'Standard', prices: [{ amount: 3500, currency_code: 'usd' }], inventory_quantity: 10 },
    ],
    tags: [{ value: 'necklaces' }, { value: 'red' }],
  },
  {
    id: '6',
    title: 'Prosperity Bracelet Set',
    description: 'A beautiful set of three coordinating bracelets featuring all the colors of the Kenyan flag. Perfect for stacking or gifting. Each bracelet can be worn individually or together for a bold, layered look. Comes in an elegant gift box.',
    handle: 'prosperity-bracelet-set',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v6', title: 'One Size', prices: [{ amount: 5500, currency_code: 'usd' }], inventory_quantity: 8 },
    ],
    tags: [{ value: 'bracelets' }, { value: 'green' }, { value: 'set' }],
  },
  {
    id: '7',
    title: 'Maasai Beadwork T-Shirt - Black',
    description: 'Celebrate Maasai culture with this premium 100% cotton t-shirt featuring an authentic beadwork pattern design. The print showcases traditional Maasai colors and patterns, making it a perfect blend of heritage and modern fashion. Soft, comfortable, and ethically made. Unisex sizing.',
    handle: 'maasai-beadwork-tshirt-black',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v7-s', title: 'Small', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 15 },
      { id: 'v7-m', title: 'Medium', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 25 },
      { id: 'v7-l', title: 'Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 20 },
      { id: 'v7-xl', title: 'X-Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 12 },
    ],
    tags: [{ value: 'tshirts' }, { value: 'black' }, { value: 'apparel' }],
  },
  {
    id: '8',
    title: 'Kenyan Flag T-Shirt',
    description: 'Show your Kenyan pride with this vibrant t-shirt featuring the colors of the national flag in a modern beaded pattern design. Made from 100% organic cotton, this shirt is both comfortable and sustainable. Perfect for everyday wear or special occasions. The design celebrates Kenyan heritage with style.',
    handle: 'kenyan-flag-tshirt',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v8-s', title: 'Small', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 18 },
      { id: 'v8-m', title: 'Medium', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 30 },
      { id: 'v8-l', title: 'Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 25 },
      { id: 'v8-xl', title: 'X-Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 15 },
    ],
    tags: [{ value: 'tshirts' }, { value: 'red' }, { value: 'apparel' }, { value: 'featured' }],
  },
  {
    id: '9',
    title: 'Heritage Beadwork T-Shirt - White',
    description: 'A timeless white t-shirt adorned with a vibrant Maasai beadwork pattern across the chest. The design features authentic traditional colors and symbols. Made from premium ringspun cotton for superior comfort and durability. Unisex fit that looks great on everyone.',
    handle: 'heritage-beadwork-tshirt-white',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v9-s', title: 'Small', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 20 },
      { id: 'v9-m', title: 'Medium', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 28 },
      { id: 'v9-l', title: 'Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 22 },
      { id: 'v9-xl', title: 'X-Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 14 },
    ],
    tags: [{ value: 'tshirts' }, { value: 'white' }, { value: 'apparel' }],
  },
  {
    id: '10',
    title: 'Warrior Spirit T-Shirt - Green',
    description: 'Channel the strength of Maasai warriors with this striking green t-shirt. Features a bold beadwork-inspired graphic that represents courage and tradition. Made from eco-friendly cotton blend. Perfect for those who want to make a statement while supporting sustainable fashion.',
    handle: 'warrior-spirit-tshirt-green',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v10-s', title: 'Small', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 16 },
      { id: 'v10-m', title: 'Medium', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 24 },
      { id: 'v10-l', title: 'Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 20 },
      { id: 'v10-xl', title: 'X-Large', prices: [{ amount: 2800, currency_code: 'usd' }], inventory_quantity: 10 },
    ],
    tags: [{ value: 'tshirts' }, { value: 'green' }, { value: 'apparel' }],
  },
  {
    id: '11',
    title: 'Sunset Beaded Bracelet',
    description: 'Inspired by the beautiful Kenyan sunsets, this bracelet features warm orange, red, and gold beads arranged in traditional patterns. Each piece is unique and handmade by Maasai women artisans. Adjustable clasp for perfect fit. The warm colors evoke the stunning African landscape.',
    handle: 'sunset-beaded-bracelet',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v11', title: 'Adjustable', prices: [{ amount: 2200, currency_code: 'usd' }], inventory_quantity: 22 },
    ],
    tags: [{ value: 'bracelets' }, { value: 'red' }],
  },
  {
    id: '12',
    title: 'Savanna Statement Necklace',
    description: 'A stunning multi-strand necklace featuring earth-toned beads that capture the essence of the African savanna. This statement piece combines traditional Maasai beadwork with contemporary style. Perfect for special occasions or to elevate any outfit. Makes a bold fashion statement.',
    handle: 'savanna-statement-necklace',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v12', title: 'Standard', prices: [{ amount: 5800, currency_code: 'usd' }], inventory_quantity: 8 },
    ],
    tags: [{ value: 'necklaces' }, { value: 'black' }, { value: 'featured' }],
  },
  {
    id: '13',
    title: 'Tribal Elegance Earrings',
    description: 'Elegant drop earrings featuring intricate Maasai beadwork in traditional patterns. Lightweight and comfortable for all-day wear. Each pair is handcrafted and slightly unique. Hypoallergenic hooks suitable for sensitive ears. Available in two stunning color combinations.',
    handle: 'tribal-elegance-earrings',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v13-rb', title: 'Red & Black', prices: [{ amount: 1800, currency_code: 'usd' }], inventory_quantity: 25 },
      { id: 'v13-gw', title: 'Green & White', prices: [{ amount: 1800, currency_code: 'usd' }], inventory_quantity: 20 },
    ],
    tags: [{ value: 'earrings' }, { value: 'red' }],
  },
  {
    id: '14',
    title: 'Cultural Pride Ankle Bracelet',
    description: 'A delicate anklet featuring small glass beads in Kenyan flag colors with a traditional Maasai shield charm. Perfect for beach days or adding a touch of culture to any outfit. Adjustable length with secure clasp. Waterproof and durable for everyday wear.',
    handle: 'cultural-pride-ankle-bracelet',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v14', title: 'Adjustable', prices: [{ amount: 1600, currency_code: 'usd' }], inventory_quantity: 35 },
    ],
    tags: [{ value: 'anklets' }, { value: 'green' }],
  },
  {
    id: '15',
    title: 'Artisan Collection Gift Set',
    description: 'A beautifully packaged gift set featuring a coordinating bracelet, necklace, and pair of earrings. All pieces are handcrafted by the same artisan for perfect harmony. Comes in an elegant gift box with information about the artisan and Maasai beadwork traditions. Perfect for gifting or treating yourself to a complete collection.',
    handle: 'artisan-collection-gift-set',
    thumbnail: '/placeholder.svg',
    variants: [
      { id: 'v15-h', title: 'Heritage Collection', prices: [{ amount: 8900, currency_code: 'usd' }], inventory_quantity: 5 },
      { id: 'v15-p', title: 'Pride Collection', prices: [{ amount: 8900, currency_code: 'usd' }], inventory_quantity: 6 },
    ],
    tags: [{ value: 'sets' }, { value: 'featured' }, { value: 'gift' }],
  },
]
